### ISSUE TITLE
Метод mostPlayerByGenre класса Player возращает null вместо названия игры

### ISSUE THREAD

**Issue by Butanya** [serj-43/GameTeamProject#10]
# Описание
Метод mostPlayerByGenre класса Player (возвращает игру заданного жанра в которую играли больше всего) возращает null вместо названия игры. Игры заданного жанра и количество часов игры в них предустановлено

# Локация дефекта
https://github.com/serj-43/GameTeamProject/blob/b054d4880afd36e6cf366e1a2f6687fd5af38426/src/main/java/ru/netology/Player.java#L59

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/serj-43/GameTeamProject) в IDEA
2. Запустить тест mostPlayerByGenre
3. Посмотреть вывод в консоли

*Ожидаемый результат:* Тест проходит 
*Фактический результат:* Тест не проходит  (Expected: Нетология Баттл Онлайн, Actual: null)

# Скриншот
![image](https://user-images.githubusercontent.com/102555902/179405244-66d7e471-c1d5-4fae-b8f9-282a01585c26.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2022.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by serj-43** [comment]
Добавил реализацию метода mostPlayerByGenre согласно описания:
"Метод принимает жанр и возвращает игру этого жанра, в которую играли больше всего. Если в игры этого жанра не играли, возвращается null"

Необходимо учесть в тесте shouldReturnMostPlayedGameByGenre1Genre, что возвращаемое значение метода - игра класса Game
