### ISSUE TITLE
Метод sumGenre класса Player при подсчете количества часов всегда возвращает 0

### ISSUE THREAD

**Issue by Butanya** [serj-43/GameTeamProject#2]
# Описание
Метод sumGenre класса Player (принимает жанр игры и суммирует время, проигранное во все игры этого жанра этим игроком) всегда возвращает 0 вместо количества часов.

# Локация дефекта
https://github.com/serj-43/GameTeamProject/blob/d7981dce014eaa6cbb87ccaa21191d94f50e4e52/src/test/java/ru/netology/PlayerTest.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/serj-43/GameTeamProject) в IDEA
2. Запустить тест shouldSumGenreIfOneGame
3. Посмотреть вывод в консоли

*Ожидаемый результат:* Тест проходит (Аctual: 3, Expected: 3)
*Фактический результат:* Тест не проходит  (Аctual: 0, Expected: 3)

# Скриншот
![TP#1](https://user-images.githubusercontent.com/102555902/179367417-0dd23e29-e208-43ca-9b7d-57d3d6d74ac6.JPG)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2022.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by serj-43** [comment]
Баг в методе play, при добавлении времени игры, текущее значение не суммировалось с hours, пофиксил
