### ISSUE TITLE
Meтод Play класса Player не выкидывает RuntimeException для незарегистрированной игры

### ISSUE THREAD

**Issue by Butanya** [serj-43/GameTeamProject#3]
# Описание
Метод Play класса Player не выкидывает RuntimeException при попытке посчитать суммарное количество часов, проигранное в незарегистрированную игру

# Локация дефекта
https://github.com/serj-43/GameTeamProject/blob/b054d4880afd36e6cf366e1a2f6687fd5af38426/src/main/java/ru/netology/Player.java#L33

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/serj-43/GameTeamProject) в IDEA
2. Запустить тест shouldTrowExceptionIfNotInstalled
3. Посмотреть вывод в консоли

*Ожидаемый результат:* Тест проходит 
*Фактический результат:* Тест не проходит  (RuntimeException to be thrown, but nothing was thrown)

# Скриншот
![TP#3](https://user-images.githubusercontent.com/102555902/179369211-bda1aae9-3d05-4fdc-a944-63168c8682b6.JPG)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2022.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by serj-43** [comment]
Пофикшено, добавил ошибку для неустановленной игры (NotInstalledException). Так же добавил ошибку для повторной установки (AlreadyInstalledException)
