### ISSUE TITLE
Метод play класса Player при подсчете количества часов для зарегистрированной игры возвращает 0

### ISSUE THREAD

**Issue by Butanya** [serj-43/GameTeamProject#9]
# Описание
Метод play класса Player (возвращает суммарное количество часов, проигранное в опреденную игру, если она установлена)  возвращает 0 вместо количества часов.

# Локация дефекта
  https://github.com/serj-43/GameTeamProject/blob/b054d4880afd36e6cf366e1a2f6687fd5af38426/src/main/java/ru/netology/Player.java#L33 

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/serj-43/GameTeamProject) в IDEA
2. Запустить тест shouldSumHoursIfGameInstalled
3. Посмотреть вывод в консоли

*Ожидаемый результат:* Тест проходит (Аctual: 3, Expected: 3)
*Фактический результат:* Тест не проходит  (Аctual: 0, Expected: 3)

# Скриншот
![image](https://user-images.githubusercontent.com/102555902/179403807-e9295a2f-c399-4d25-a88c-9e7f980cadaa.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2022.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by serj-43** [comment]
Не баг

player.play(game, 3);
int expected = 3;
int actual = player.play(game, 3);

в игру играли 6 часов

**Comment by Butanya** [comment]
играли 6, а возвращал 0
